# Generated by Django 2.1.3 on 2018-11-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActa', models.DateField()),
                ('numActa', models.IntegerField()),
                ('copActa', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
