# Generated by Django 2.1.3 on 2018-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='copActa',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
