# Generated by Django 2.1.3 on 2018-11-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actas', '0001_initial'),
        ('formapagos', '0004_cheques_copchq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombCompSoc', models.CharField(max_length=70)),
                ('rutSoc', models.CharField(max_length=10)),
                ('domicSoc', models.CharField(max_length=100)),
                ('fecNacSoc', models.DateField(null=True)),
                ('mailSoc', models.EmailField(blank=True, max_length=254, null=True)),
                ('celSoc', models.CharField(max_length=12)),
                ('telSoc', models.CharField(blank=True, max_length=12, null=True)),
                ('profecSoc', models.CharField(blank=True, max_length=30, null=True)),
                ('trabSoc', models.CharField(blank=True, max_length=30, null=True)),
                ('edadSoc', models.IntegerField()),
                ('nacionalidadSoc', models.CharField(max_length=30)),
                ('estCivSoc', models.CharField(max_length=10)),
                ('conySoc', models.CharField(blank=True, max_length=70, null=True)),
                ('numHijMenSoc', models.IntegerField(blank=True, null=True)),
                ('poctSoc', models.CharField(blank=True, max_length=50, null=True)),
                ('ocsSoc', models.CharField(blank=True, max_length=50, null=True)),
                ('catTenSoc', models.CharField(blank=True, max_length=50, null=True)),
                ('numCas', models.CharField(blank=True, max_length=50, null=True)),
                ('cuotInc', models.IntegerField(blank=True, null=True)),
                ('cuotSoc', models.IntegerField(blank=True, null=True)),
                ('totPag', models.IntegerField(blank=True, null=True)),
                ('tipoSoc', models.CharField(blank=True, max_length=50, null=True)),
                ('fecSolic', models.DateField(blank=True, null=True)),
                ('estSolic', models.CharField(blank=True, max_length=40, null=True)),
                ('fecAcept', models.DateField(blank=True, null=True)),
                ('infSolic', models.TextField()),
                ('fotoSoc', models.ImageField(upload_to='')),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actas.Acta')),
                ('formPaInsc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapagos.FormaPago')),
                ('primSocFe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='socios.Socio')),
                ('secSocFe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='socios.Socio')),
                ('socPatr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='socios.Socio')),
            ],
        ),
    ]
