# Generated by Django 2.1.3 on 2018-11-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='celSoc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='edadSoc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='estSolic',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fotoSoc',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='socio',
            name='infSolic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
