# Generated by Django 2.1.3 on 2018-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='medioPago',
            field=models.CharField(max_length=15),
        ),
    ]
