# Generated by Django 2.1.3 on 2018-11-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapagos', '0002_auto_20181121_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titChq', models.CharField(max_length=60)),
                ('montoChq', models.IntegerField()),
                ('bcoChq', models.CharField(max_length=60)),
                ('fchEmChq', models.DateField()),
                ('fchInVigChq', models.DateField()),
                ('fchCobChq', models.DateField(blank=True, null=True)),
                ('cambioChq', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapagos.Cheques')),
            ],
        ),
    ]
