# Generated by Django 2.1.3 on 2018-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapagos', '0003_cheques'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques',
            name='copChq',
            field=models.ImageField(blank=True, null=True, upload_to='path_and_rename(cehques/)'),
        ),
    ]
