# Generated by Django 2.1.3 on 2018-11-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapagos', '0004_cheques_copchq'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheques',
            name='serieChq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='bcoChq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='fchEmChq',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='fchInVigChq',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='montoChq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cheques',
            name='titChq',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
